### ISSUE TITLE
Error when mapping a double value in a result set to a float

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/module-ballerinax-cassandra#13]
**Description:**
When mapping a double value in a data table, from a select operation, following error occurs.

{code}
error: error, message: codec not found for requested operation: [double <-> java.lang.Float]
{code}

https://github.com/datastax/java-driver/blob/3.4.0/driver-core/src/main/java/com/datastax/driver/core/AbstractGettableByIndexData.java#L69
This seems to be occurring when trying to deserialize a double value as a float. 

Need a way to retrieve a double.
**Affected Product Version:**
0.5.2

**Comment by anupama-pathirage** [comment]
Closing this issue as we no longer maintain this codebase.
