### ISSUE TITLE
Add support for keepAlive, reuseAddress, tcpNoDelay connection parameters

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/module-ballerinax-cassandra#16]
**Description:**
Driver do not set these by default. It takes the default values of the underlying layer.
But if we take the inputs as booleans and if the value set in the bal file is "false", we wouldn't know
if it was set by the user or not. So need to decide how to handle this.

**Comment by anupama-pathirage** [comment]
Closing this issue as we no longer maintain this codebase.
